yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path(
        "posts/<int:post_id>/comment/",
        login_required(views.add_comment),
        name="add_comment",
    ),
    path("create/", login_required(views.create_post), name="create_post"),
    path(
        "posts/<int:post_id>/edit/",
        login_required(views.edit_post),
        name="update_post",
    ),
    path(
        "profile/<str:username>/follow/",
        views.follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.unfollow,
        name="profile_unfollow",
    ),
    path("follow/", views.follow_index, name="follow_index"),
]

yatube/users/urls.py
from django.contrib.auth import views
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),

    path('logout/', LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),

    path('password_change/', PasswordChangeView.as_view(
         template_name='users/password_change_form.html'
         ), name='password_change_form'),
    path('password_change/done/', PasswordResetDoneView.as_view(
         template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view
         (template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view
         (template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view
         (template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("auth/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
]

handler404 = "core.views.page_not_found"
handler403 = "core.views.permission_denied"
handler500 = "core.views.server_error"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-dark">© {% now "Y" %} Copyright <span style="color: red">[.Py]</span>tube</span>
  </div>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header class="p-3 mb-2 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="{% url 'posts:index' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none"
        data-toggle="tooltip" data-placement="bottom" title="На главную">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" />
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link px-2 text-secondary {% if view_name == 'about:author' %} text-white {% endif %}"
            href="{% url 'about:author' %}"> Про автора <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
              fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
              <path
                d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z">
              </path>
            </svg> </a>
        </li>
        <li class="nav-item">
          <a class=" nav-link px-2 text-secondary {% if view_name == 'about:tech' %} text-white {% endif %}"
            href="{% url 'about:tech' %}">Про стэк <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
              fill="currentColor" class="bi bi-layers-half" viewBox="0 0 16 16">
              <path
                d="M8.235 1.559a.5.5 0 0 0-.47 0l-7.5 4a.5.5 0 0 0 0 .882L3.188 8 .264 9.559a.5.5 0 0 0 0 .882l7.5 4a.5.5 0 0 0 .47 0l7.5-4a.5.5 0 0 0 0-.882L12.813 8l2.922-1.559a.5.5 0 0 0 0-.882l-7.5-4zM8 9.433 1.562 6 8 2.567 14.438 6 8 9.433z">
              </path>
            </svg>
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link px-2 text-secondary{% if view_name == 'posts:create_post' %} text-white {% endif %}"
            href="{% url 'posts:create_post' %}">Новая запись <svg xmlns="http://www.w3.org/2000/svg" width="16"
              height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path
                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z">
              </path>
              <path fill-rule="evenodd"
                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z">
              </path>
            </svg> </a>
        </li>
      </ul>
      <div class="text-end">
        Добро пожаловать, {{ user.username }}!
        <a href="{% url 'users:password_change_form' %}"><button type="button" class="btn btn-outline-light me-2">
            Изменить пароль
          </button></a>
        <a href="{% url 'users:logout' %}"><button type="button" class="btn btn-warning">Выйти</button></a>
      </div>
      {% else %}
      </ul>
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-end">
        <a href="{% url 'users:login' %}"><button type="button" class="btn btn-outline-light me-2">
            Войти
          </button></a>
        <a href="{% url 'users:signup' %}"><button type="button" class="btn btn-warning">Регистрация</button></a>
      </div>
      {% endif %}
      {% endwith %}
    </div>
  </div>
</header>