yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path(
        "posts/<int:post_id>/comment/",
        login_required(views.add_comment),
        name="add_comment",
    ),
    path("create/", login_required(views.create_post), name="create_post"),
    path(
        "posts/<int:post_id>/edit/",
        login_required(views.edit_post),
        name="update_post",
    ),
    path(
        "profile/<str:username>/follow/",
        views.follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.unfollow,
        name="profile_unfollow",
    ),
    path("follow/", views.follow_index, name="follow_index"),
]

yatube/yatube/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("auth/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
]

handler404 = "core.views.page_not_found"
handler403 = "core.views.permission_denied"
handler500 = "core.views.server_error"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CoreModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, null=False)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(CoreModel):
    text = models.TextField(verbose_name="Пост", help_text="Введите текст")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
    )
    image = models.ImageField(
        ("Фото"),
        upload_to="posts/",
        blank=True,
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts",
        verbose_name="Группа",
        help_text="Выберите группу",
    )

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    text = models.TextField(verbose_name="Оставить комментарий")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self) -> str:
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name="follower",
        on_delete=models.CASCADE,
        verbose_name="Подписчик",
        blank=True
    )
    author = models.ForeignKey(
        User,
        related_name="following",
        on_delete=models.CASCADE,
        verbose_name="Автор",
        blank=True
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name="unique_subscription")]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "text",
            "group",
            "image",
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        widgets = {
            "text": forms.Textarea(attrs={"rows": 3, "cols": 15}),
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

LIM = settings.PAGINATION_LIMIT


@cache_page(20)
@vary_on_cookie
def index(request):
    posts = Post.objects.select_related("group", "author").all()
    paginator = Paginator(posts, LIM)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    template = "posts/index.html"
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    paginator = Paginator(group.posts.select_related("author").all(), LIM)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "group": group,
        "page_obj": page_obj,
    }
    template = "posts/group_list.html"
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    is_following = False
    if not request.user.is_anonymous and request.user != author:
        is_following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
    paginator = Paginator(author.posts.select_related("group").all(), LIM)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "author": author,
        "page_obj": page_obj,
        "following": is_following,
    }
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related(
            "author",
            "group",
        ),
        id=post_id,
    )
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    comments = post.comments.filter(post=post_id).select_related("author")
    context = {"post": post, "form": form, "comments": comments}
    return render(request, "posts/post_detail.html", context)


@login_required
def create_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", request.user.username)
    return render(request, "posts/create_post.html", {"form": form})


@login_required
def edit_post(request, post_id):
    cur_post = get_object_or_404(Post, id=post_id)

    if cur_post.author != request.user:
        return redirect("posts:post_detail", post_id)

    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=cur_post
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    return render(
        request,
        "posts/create_post.html",
        {"form": form, "is_edit": True, "post_id": post_id},
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id)


@login_required
def follow(request, username):
    """
    Add new author to user's subscription list
    """
    author = get_object_or_404(User, username=username)
    user = request.user
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect("posts:profile", username)


@login_required
def unfollow(request, username):
    """
    Remove author from user's subscription list
    """
    author = get_object_or_404(User, username=username)
    user = request.user
    subscription = Follow.objects.filter(user=user, author=author)
    subscription.delete()
    return redirect("posts:profile", username)


@login_required
def follow_index(request):
    """
    Will dislpay posts only from user's subscriptions
    """
    posts = (
        Post.objects.filter(author__following__user=request.user)
        .select_related(
            "author",
            "group",
        )
    )
    paginator = Paginator(posts, LIM)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "posts/follow.html", context)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit%} Изменить запись {% else %} Добавить запись {% endif %}
{% endblock title %}
{% block content %}
<main>
  <div class="container py-3">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit%} Измените запись {% else %} Новая запись {% endif %}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="POST" enctype="multipart/form-data"
              action="{% if is_edit %} {% url 'posts:update_post' post_id %} {% else %} {% url 'posts:create_post' %} {% endif %}">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }} {% if field.field.required %}
                    <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field }}
                  <div>
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} Изменить {% else %} Добавить {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load humanize %}
{% block title %}
  Pytube
{% endblock title %}
{% block content %}
  <div class="container py-3">
    <h1>{{ 'Избранные публикации:' }}</h1>
    {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
      <div class="card">
        <h3 class="card-header" > 
          <a href="{% url 'posts:profile' post.author.username %}"> 
            {% if post.author.get_full_name != '' %}
              {{ post.author.get_full_name }}
              {% else %}
              {{ post.author.username }}
            {% endif %}
          </a>
        </h3>
          <div class="card-body">
          <p class="card-text"> {{ post.text|linebreaks }}
          </p>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <hr>
          <h6 class="card-text">{{ post.pub_date|naturaltime}} </h6>
          {% if post.group %}
            <p> в сообществе
            <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group }} </a> 
            </p>
          {% endif %}
          <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Обсудить</a>
        </div>
      </div>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock content %}
</div>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load thumbnail %}
{% block title %}
  Записи сообщества
{% endblock %}
{% block content %}
  <div class="container py-3">
    <h3>{{ group.title }}</h3>
    <p>{{ group.description|linebreaks }}</p>
    {% for post in page_obj %}
      <div class="card">
        <h3 class="card-header" > 
          <a href="{% url 'posts:profile' post.author.username %}"> 
            {% if post.author.get_full_name != '' %}
              {{ post.author.get_full_name }}
              {% else %}
              {{ post.author.username }}
            {% endif %}
          </a>
        </h3>
          <div class="card-body">
          <p class="card-text"> {{ post.text|linebreaks }}
          </p>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <hr>
          <h6 class="card-text">{{ post.pub_date|naturaltime}} </h6>
          {% if post.group %}
            <p> в сообществе
            <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group }} </a> 
            </p>
          {% endif %}
          <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Обсудить</a>
        </div>
      </div>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load humanize %}
{% load thumbnail %}
{% block title %}
  Pytube
{% endblock title %}
{% block content %}
  <div class="container py-3">
    <h1>{{ 'Последние публикации:' }}</h1>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      <div class="card">
        <h3 class="card-header" > 
          <a href="{% url 'posts:profile' post.author.username %}"> 
            {% if post.author.get_full_name != '' %}
              {{ post.author.get_full_name }}
              {% else %}
              {{ post.author.username }}
            {% endif %}
          </a>
        </h3>
          <div class="card-body">
          <p class="card-text"> {{ post.text|linebreaks }}
          </p>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <hr>
          <h6 class="card-text">{{ post.pub_date|naturaltime}} </h6>
          {% if post.group %}
            <p> в сообществе
            <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group }} </a> 
            </p>
          {% endif %}
          <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Обсудить</a>
        </div>
      </div>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock content %}
</div>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}
Пост [{{ post.text|truncatechars:30 }}]
{% endblock title %}
{% block content %}
<main>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: <a href="{% url 'posts:profile' post.author.username %}"> {{ post.author.get_full_name|capfirst }} </a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>{{ post.text|linebreaks }}</p>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% if user == post.author %}
      <form style="display: inline" action="{% url 'posts:update_post' post.id %}">
        <button>Редактировать</button>
      </form>
      {% endif %}
      {% if user.is_authenticated %}
      <div class="container xs">
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2" placeholder="Комментарий...">
                {{ form.text| addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      </div>
      <hr>
      {% endif %}
      {% if comments.count == 0 %}
      <h5>Оставьте первый комментарий</h5>
      {% else %}
      <h5>Комментарии:</h5>
      <div class="container xs">
      {% for comment in comments %}
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">
            <a href="{% url 'posts:profile' comment.author.username %}" class="link-dark"> {{ comment.author.username }}
            </a>
          </h5>
          <h6 class="card-subtitle mb-2 text-muted"> {{ comment.created|date:"d E Y" }} </h6>
          <p class="card-text"> {{ comment.text }} </p>
        </div>
      </div>
      <br>
      {% endfor %}
      </div>
      {% endif %}
    </article>
  </div>
</main>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load humanize %}
{% block title %}
Профайл пользователя {{ author|capfirst }}
{% endblock title %}
{% block content %}
<main>
  <div class="container py-3">
    <div class="row justify">
      <div class="col-3">
        <h1 class="text-secondary">{{ author|capfirst }}</h1>
        <h5b class="text-secondary">Всего постов: {{ author.posts.count }}</h5>
      </div>
      <div class="col-sm">
        {% if user.is_authenticated and request.user != author %}
        {% if following %}
        <a class="btn btn-s btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
          Отписаться
        </a>
        {% else %}
        <a class="btn btn-s btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">
          Подписаться
        </a>
        {% endif %}
        {% endif %}
      </div>
    </div>
    <br>
    {% for post in page_obj %}
    <div class="card">
      <h3 class="card-header">
        <a href="{% url 'posts:profile' post.author.username %}"> 
            {% if post.author.get_full_name != '' %}
              {{ post.author.get_full_name }}
              {% else %}
              {{ post.author.username }}
            {% endif %}
          </a>
      </h3>
      <div class="card-body">
        <p class="card-text"> {{ post.text|linebreaks }}
        </p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <hr>
        <h6 class="card-text">{{ post.pub_date|naturaltime}} </h6>
        {% if post.group %}
        <p> в сообществе
          <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group }} </a>
        </p>
        {% endif %}
        <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary">Обсудить</a>
      </div>
    </div>
    {% if not forloop.last %}
    <hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
</main>
{% endblock content %}